services:
  app:
    container_name: app
    restart: unless-stopped
    #build: .
    #image: app:latest
    image: ghcr.io/qwqw-333/app-test:v0.0.5
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      backend-db:
        condition: service_healthy
    networks:
      - public
      - backend-internal

  backend-db:
    container_name: backend-db
    restart: unless-stopped
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${db_user} -d ${db_name}" ]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - backend-internal

networks:
  public:
    name: public
  backend-internal:
    name: backend-internal
